name: MSGAIFinal
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - matplotlib
  - scipy
  - pillow
  - tqdm
  - seaborn
  - ipykernel
  - datasets
  - huggingface_hub
  - transformers
  - pytorch=2.2.0  
  - torchvision=0.17.0
  - pytorch-cuda=11.8  
  - pip:
      - accelerate==1.11.0
      - diffusers==0.31.0
      - peft==0.18.0
